name: CI test

on: 
    pull_request:
        branches:
        - main 
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate JSON
        uses: walbo/validate-json@v1.1.0
        with:
          files: repository.json 
          schema: repository.schema.json
          fail-on-missing-schema: true
          schema-version: draft2020
          strict: true
          allow-matching-properties: false
          allow-union-types: true